### ISSUE TITLE
flatten Matrixes that are passed to `log_histogram`

### ISSUE THREAD

**Issue by oxinabox** [PhilipVinc/TensorBoardLogger.jl#4]
Basically if someone passes a matrix to `log_histogram`,
it would be good to call `vec` on it.

I believe this is the behavour of tensorboard in TensorFlow.

**Comment by shashikdm** [comment]
yes I agree with it.

**Comment by shashikdm** [comment]
i think it should be more general and accept Nd array. I'm looking for operation similar to numpy's arr.reshape(-1)

**Comment by PhilipVinc** [comment]
Of course I agree with the change.

But I wonder if, instead of flattening N-d arrays at a low level (when we create the `histogram_summary`) such as the PR you proposed of @shashikdm , if it wouldn't be better to do it at the level of `preprocess` (see #5 and the `logger_interface` branch) so that if an user wants he can change the behaviour of the flattening to something else.
