### ISSUE TITLE
A method to construct a logger that uses the first available name that avoids overwriting

### ISSUE THREAD

**Issue by oxinabox** [PhilipVinc/TensorBoardLogger.jl#6]
The behavour of TensorFlow.jl if you have a logger set to path `mypath`
is to try `mypath2` then `mypath3` and so forth until it finds a free name.

It might make sense to have overwrite take 3 options:

 - Append (current behavour if false)
 - Overwrite (current behavour if true)
 - IncrementFilename (my suggested behavour)

**Comment by PhilipVinc** [comment]
Good idea. 
The standard way to do this would be with a symbol, so something along the lines of `:append`, `:overwrite` and `:increment`?

**Comment by oxinabox** [comment]
Those names sound good, but,
that kind of use of symbols is an antipattern and a holdover from before julia had Enums.

I suggest either Enums or singleton types, if you want to dispatch on it.
Dispatching on it seems over-engineered.
Therefor **Enums.**

**Comment by PhilipVinc** [comment]
Solved by [#9be2eb0](https://github.com/PhilipVinc/TensorBoardLogger.jl/commit/9be2eb0805d16d7c3e768f5affc0b11b7dc649c9) .

The enum values are, at the moment, `tb_overwrite`, `tb_append`, and `tb_increment`. I'm not very happy with this naming, but I think that exporting some very generic names such as `overwrite`, `append` and `increment` would not be wise.

Also, I should have a look at how the `increment` behavior works in tensor board so that we can match it. At the moment if `logdir="test"`, then subsequent runs will be `test_1`, `test_2`, etc... which is kind of inconsistent as the first run will just be in a folder named `test`.
